#!/usr/bin/with-contenv bash

# Check for curl, jq, iptables
if [ ! -f /usr/bin/curl ] || [ ! -f /usr/bin/jq ] || [ ! -f /usr/bin/iptables ]; then
  echo "[mod-tailscale] Curl/JQ/IPTables was not found on this system"
  if [ -f /usr/bin/apt ]; then
    ## Ubuntu
    apt-get update
    apt-get install --no-install-recommends -y \
      curl \
      jq \
      iptables
  elif [ -f /sbin/apk ]; then
    # Alpine
    apk add --no-cache \
      curl \
      jq \
      iptables
  fi
fi

set -euo pipefail

dir="$(mktemp -d)"
pushd .
cd "${dir}"

GOARCH=""

case `uname -m` in
    x86_64)
        GOARCH="amd64"
        ;;

    aarch64)
        GOARCH="arm64"
        ;;
    riscv64)
        GOARCH="riscv64"
        ;;
    armv7l)
        GOARCH="arm"
        ;;
    *)
        echo "Unknown CPU type $(uname -m), please file a bug at https://github.com/tailscale-dev/docker-mod"
        exit 125
        ;;
esac

tarball="$(curl 'https://pkgs.tailscale.com/stable/?mode=json' | jq -r .Tarballs.${GOARCH})"
version="$(echo ${tarball} | cut -d_ -f2)"

echo "[mod-tailscale] Downloading Tailscale ${version}"

curl "https://pkgs.tailscale.com/stable/${tarball}" -o tailscale.tgz

tar xzf tailscale.tgz

cp -vrf "tailscale_${version}_${GOARCH}"/tailscale /usr/bin/tailscale
cp -vrf "tailscale_${version}_${GOARCH}"/tailscaled /usr/sbin/tailscaled

popd
rm -rf "${dir}"
