# https://hub.docker.com/r/linuxserver/sonarr
FROM --platform=linux/arm lscr.io/linuxserver/sonarr:3.0.8.1507-ls151

# Update this date to re-run apt-get.
LABEL package.date=2023-08-31

RUN \
 echo "**** install packages ****" && \
 apt-get update && \
 apt-get dist-upgrade -y && \
 apt-get install -y \
	nfs-common \
	iptables && \
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
	/tmp/* \
	/var/tmp/* \
	/var/lib/apt/lists/*

# add local files
COPY root/ /
