# https://hub.docker.com/r/linuxserver/radarr
FROM --platform=linux/arm lscr.io/linuxserver/radarr:latest

RUN \
 echo "**** install packages ****" && \
 apt-get update && \
 apt-get install -y \
        nfs-common && \
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
	/tmp/* \
	/var/tmp/*

# add local files
COPY root/ /
