# https://hub.docker.com/_/traefik
# FROM --platform=linux/arm traefik:latest
FROM ghcr.io/chukysoria/traefik:latest

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
    nano \
	iptables && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*

COPY traefik-tailscale/ /config