# https://hub.docker.com/r/linuxserver/radarr
FROM --platform=linux/arm lscr.io/linuxserver/radarr:latest

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	nfs-utils && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*

# add local files
COPY root/ /
