# syntax=docker/dockerfile:1

# FROM --platform=linux/arm lscr.io/linuxserver/sonarr:3.0.8.1507-ls151
FROM ghcr.io/chukysoria/sonarr:latest

RUN \
 echo "**** install packages ****" && \
 apt-get update && \
 apt-get install -y \
	nfs-common \
	iptables && \
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
	/tmp/* \
	/var/tmp/* \
	/var/lib/apt/lists/*

# add local files
COPY root/ /
