version: '2.1'

volumes:
    adguardhome_work:
    adguardhome_conf:
    sonarr_conf:
    radarr_conf:
    bazarr_conf:
    homeassistant_conf:
    swag_conf:
    jackett_conf:
    nodered_conf:

services:

    adguard:
        build:
            context: .
            dockerfile: Dockerfile-adguard
        network_mode: host
        privileged: true
        volumes:
            - 'adguardhome_work:/opt/adguardhome/work:rw'
            - 'adguardhome_conf:/opt/adguardhome/conf:rw'
    
    sonarr:
        build:
            context: .
            dockerfile: Dockerfile-sonarr
        privileged: true
        volumes:
            - 'sonarr_conf:/config:rw'
        ports:
            - 8989:8989
        networks: 
            - web_net

    radarr:
        build: 
            context: .
            dockerfile: Dockerfile-radarr
        privileged: true
        volumes:
            - 'radarr_conf:/config:rw'
        #ports:
        #    - 7878:7878
        networks: 
            - web_net
    
    bazarr:
        build: 
            context: .
            dockerfile: Dockerfile-bazarr
        privileged: true
        volumes:
            - 'bazarr_conf:/config:rw'
        #ports:
        #    - 6767:6767
        depends_on: 
            - sonarr
            - radarr
        networks: 
            - web_net

    homeassistant:
        build:
            context: .
            dockerfile: Dockerfile-homeassistant
        network_mode: host
        volumes:
            - 'homeassistant_conf:/config:rw'

    swag:
        image: linuxserver/swag:arm32v7-latest
        cap_add:
            - NET_ADMIN
        volumes:
            - swag_conf:/config
        ports:
            - 443:443
            - 80:80 #optional
        networks: 
            - web_net

    duckdns:
        image: linuxserver/duckdns:arm32v7-latest

    jackett:
        image: linuxserver/jackett:arm32v7-latest
        environment:
            - AUTO_UPDATE=false
        volumes:
            - 'jackett_conf:/config:rw'
        # ports:
        #     - 9117:9117
        networks: 
            - web_net
    
    node-red:
        build:
            context: .
            dockerfile: Dockerfile-nodered
        # ports:
        #    - 1880:1880
        network_mode: host
        volumes:
            - nodered_conf:/data:rw

    node-red:
        build:
            context: .
            dockerfile: Dockerfile-nodered
        network_mode: host
        volumes:
        - 'nodered_conf:/data:rw'
        
networks: 
    web_net:
        driver: bridge