# https://hub.docker.com/r/linuxserver/qbittorrent
FROM --platform=linux/arm lscr.io/linuxserver/qbittorrent:latest

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	nfs-utils && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*

# Add VueTorrent intergace
ARG VUETORRENT_VERSION=0.18.2
RUN curl -fsSL "https://github.com/wdaan/vuetorrent/releases/download/v${VUETORRENT_VERSION}/vuetorrent.zip" > "/tmp/vuetorrent.zip" && \
    unzip "/tmp/vuetorrent.zip" -d "/qbt" && \
    rm "/tmp/vuetorrent.zip" && \
    chmod -R u=rwX,go=rX "/qbt/vuetorrent"

# add local files
COPY root/ /
