version: '2.4'

# Torrentillo Pi compose file

volumes:
    sonarr_conf:
    bazarr_conf:
    certs:
    traefik_conf:
    duplicati:
    prowlarr_conf:
    traefik_tailscale_conf:
    # Tailscale config volumes
    ts_duplicati:
    ts_sonarr:
    ts_bazarr:
    ts_traefik:
    ts_traefik_tailscale:
    ts_jellyfin:
    ts_prowlarr:


services:
    duplicati:
        image: ghcr.io/chukysoria/duplicati:v0.2.5
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=duplicati
            - TAILSCALE_SERVE_PORT=8200
        networks:
            - web_net
        volumes:
            - duplicati:/config
            - ts_duplicati:/tsconfig
            - sonarr_conf:/source/sonarr_conf
            - bazarr_conf:/source/bazarr_conf
            - traefik_conf:/source/traefik_conf
            - prowlarr_conf:/source/prowlarr_conf
            - traefik_tailscale_conf:/source/traefik_tailscale_conf
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.duplicati.rule=Host(`duplicati.boulebar.duckdns.org`)"

    sonarr:
        image: ghcr.io/chukysoria/sonarr:v0.2.6
        cap_add:
            - SYS_ADMIN
        volumes:
            - sonarr_conf:/config:rw
            - ts_sonarr:/tsconfig
        networks:
            - web_net
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3|ghcr.io/chukysoria/linuxserver-mod-nfs:v1.0.0
            - MOD_NFS_MOUNTS=192.168.1.6:/volume1,/media
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=sonarr
            - TAILSCALE_SERVE_PORT=8989
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule=Host(`sonarr.boulebar.duckdns.org`)"

    bazarr:
        image: ghcr.io/chukysoria/bazarr:v0.4.9
        cap_add:
            - SYS_ADMIN
        volumes:
            - bazarr_conf:/config:rw
            - ts_bazarr:/tsconfig
        networks:
            - web_net
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3|ghcr.io/chukysoria/linuxserver-mod-nfs:v1.0.0
            - MOD_NFS_MOUNTS=192.168.1.6:/volume1,/media
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=bazarr
            - TAILSCALE_SERVE_PORT=6767
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bazarr.rule=Host(`bazarr.boulebar.duckdns.org`)"

    duckdns:
        image: ghcr.io/chukysoria/duckdns:v0.4.10

    traefik:
        image: ghcr.io/chukysoria/traefik:v0.3.8
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 8080:8080/tcp
            - 1900:1900/udp
            - 7359:7359/udp
        networks:
            - web_net
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=traefik
            - DOCKER_SOCK=/var/run/balena.sock
        volumes:
            - certs:/certs:rw
            - traefik_conf:/config:rw
            - ts_traefik:/tsconfig
        labels:
            - "io.balena.features.balena-socket=true"

    traefik_tailscale:
        image: ghcr.io/chukysoria/traefik:v0.3.8
        network_mode: host
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=traefik-tailscale
        volumes:             
            - traefik_tailscale_conf:/config:rw
            - ts_traefik_tailscale:/tsconfig

    jellyfin:
        image: ghcr.io/chukysoria/jellyfin:v0.2.4
        cap_add:
            - SYS_ADMIN
        networks:
            - web_net
        volumes:
            - ts_jellyfin:/tsconfig
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3|ghcr.io/chukysoria/linuxserver-mod-nfs:v1.0.0
            - MOD_NFS_MOUNTS=192.168.1.6:/volume1,/media 192.168.1.6:/volume1/video/jellyfin,/config
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=jellyfin
            - TAILSCALE_SERVE_PORT=8096
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.boulebar.duckdns.org`)"
            - "traefik.http.routers.jellyfin.service=svc-jellyfin"
            - "traefik.http.services.svc-jellyfin.loadbalancer.server.port=8096"
            - "traefik.udp.routers.jellyfinudp.entrypoints=jellyfin_locate"
            - "traefik.udp.routers.jellyfinudp.service=service-udp-jellyfin"
            - "traefik.udp.services.service-udp-jellyfin.loadbalancer.server.port=7359"
            - "traefik.udp.routers.jellyfinstreaming.entrypoints=streaming"
            - "traefik.udp.routers.jellyfinstreaming.service=service-jellyfin-streaming"
            - "traefik.udp.services.service-jellyfin-streaming.loadbalancer.server.port=1900"

    prowlarr:
        image: ghcr.io/chukysoria/prowlarr:v0.5.5
        networks:
            - web_net
        volumes:
            - prowlarr_conf:/config:rw
            - ts_prowlarr:/tsconfig
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:v1.1.3
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_USE_SSH=1
            - TAILSCALE_STATE_DIR=/tsconfig
            - TAILSCALE_HOSTNAME=prowlarr
            - TAILSCALE_SERVE_PORT=9696
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.boulebar.duckdns.org`)"

networks:
    web_net:
        driver: bridge
