version: '2.1'

volumes:
    sonarr_conf:
    radarr_conf:
    bazarr_conf:
    jackett_conf:

services:

    sonarr:
        build:
            context: .
            dockerfile: Dockerfile-sonarr
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'sonarr_conf:/config:rw'
        ports:
            - 8989:8989
        networks: 
            - web_net

    radarr:
        build: 
            context: .
            dockerfile: Dockerfile-radarr
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'radarr_conf:/config:rw'
        ports:
            - 7878:7878
        networks: 
            - web_net
    
    bazarr:
        build: 
            context: .
            dockerfile: Dockerfile-bazarr
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'bazarr_conf:/config:rw'
        ports:
            - 6767:6767
        depends_on: 
            - sonarr
            - radarr
        networks: 
            - web_net

    jackett:
        image: linuxserver/jackett:arm32v7-latest
        environment:
            - AUTO_UPDATE=false
        volumes:
            - 'jackett_conf:/config:rw'
        ports:
            - 9117:9117
        networks: 
            - web_net
   
networks:
    web_net:
        driver: bridge