# syntax=docker/dockerfile:1

# FROM --platform=linux/arm lscr.io/linuxserver/jellyfin:arm32v7-version-10.8.10-1
FROM ghcr.io/chukysoria/jellyfin:latest

RUN \
	echo "**** install packages ****" && \
	apt-get update && \
	apt-get install -y \
		nfs-common \
		iptables && \
	echo "**** cleanup ****" && \
	apt-get clean && \
	rm -rf \
	/tmp/* \
	/var/tmp/* \
	/var/lib/apt/lists/*

# add local files
COPY jellyfin/ /
