# syntax=docker/dockerfile:1

FROM ghcr.io/chukysoria/prowlarr:latest

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	iptables && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*
