version: '2.1'

volumes:
    sonarr_conf:
    radarr_conf:
    bazarr_conf:
    certs:
    traefik_conf:
    duplicati:
    prowlarr_conf:
    jellyfin_conf_tailscale:


services:
    duplicati:
        build:
            context: .
            dockerfile: Dockerfile-duplicati
        environment:
            PUID: "0"
            PGID: "0"
            CLI_ARGS: --webservice-interface=any
        networks:
            - web_net
        volumes:
            - duplicati:/config
            - sonarr_conf:/source/sonarr_conf
            - radarr_conf:/source/radarr_conf
            - bazarr_conf:/source/bazarr_conf
            - traefik_conf:/source/traefik_conf
            - prowlarr_conf:/source/prowlarr_conf
            - jellyfin_conf_tailscale:/source/jellyfin_conf_tailscale
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.duplicati.rule=Host(`duplicati.boulebar.duckdns.org`)"

    sonarr:
        build:
            context: .
            dockerfile: Dockerfile-sonarr
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'sonarr_conf:/config:rw'
        networks:
            - web_net
        environment:
            - TAILSCALE_STATE_DIR=/config
            - TAILSCALE_HOSTNAME=sonarr
            - TAILSCALE_SERVE_PORT=8989
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_FUNNEL=true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.sonarr.rule=Host(`sonarr.boulebar.duckdns.org`)"

    bazarr:
        build:
            context: .
            dockerfile: Dockerfile-bazarr
        cap_add:
            - SYS_ADMIN
        volumes:
            - 'bazarr_conf:/config:rw'
        depends_on:
            - sonarr
        networks:
            - web_net
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:latest
            - TAILSCALE_STATE_DIR=/config
            - TAILSCALE_HOSTNAME=bazarr
            - TAILSCALE_SERVE_PORT=6767
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_FUNNEL=true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.bazarr.rule=Host(`bazarr.boulebar.duckdns.org`)"

    duckdns:
        image: lscr.io/linuxserver/duckdns:arm32v7-fb872cca-ls130

    traefik:
        build:
            context: .
            dockerfile: Dockerfile-traefik
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 8080:8080/tcp
            #- 9900:9900/tcp
            #- 9901:9901/tcp
        networks:
            - web_net
        volumes:
            - "certs:/var/certs:rw"
            - "traefik_conf:/etc/traefik/:rw"
        labels:
            - "io.balena.features.balena-socket=true"

    jellyfin:
        build:
            context: .
            dockerfile: Dockerfile-jellyfin
        cap_add:
            - SYS_ADMIN
        networks:
            - web_net
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:latest
            - TAILSCALE_STATE_DIR=/var/lib/tailscale
            - TAILSCALE_HOSTNAME=jellyfin
            - TAILSCALE_SERVE_PORT=8096
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_FUNNEL=true
        volumes:
          - jellyfin_conf_tailscale:/var/lib/tailscale:rw
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.boulebar.duckdns.org`)"
            - "traefik.http.routers.jellyfin.service=svc-jellyfin"
            - "traefik.http.services.svc-jellyfin.loadbalancer.server.port=8096"
            - "traefik.udp.routers.jellyfinudp.entrypoints=jellyfin_locate"
            - "traefik.udp.routers.jellyfinudp.service=service-udp-jellyfin"
            - "traefik.udp.services.service-udp-jellyfin.loadbalancer.server.port=7359"
            - "traefik.udp.routers.jellyfinstreaming.entrypoints=streaming"
            - "traefik.udp.routers.jellyfinstreaming.service=service-jellyfin-streaming"
            - "traefik.udp.services.service-jellyfin-streaming.loadbalancer.server.port=1900"

    prowlarr:
        container_name: prolarr
        image: lscr.io/linuxserver/prowlarr:arm32v7-1.5.2.3484-ls20
        networks:
            - web_net
        volumes:
            - "prowlarr_conf:/config:rw"
        environment:
            - DOCKER_MODS=ghcr.io/chukysoria/tailscale-mod:latest
            - TAILSCALE_STATE_DIR=/config
            - TAILSCALE_HOSTNAME=prowlarr
            - TAILSCALE_SERVE_PORT=9696
            - TAILSCALE_SERVE_MODE=https
            - TAILSCALE_FUNNEL=true
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.boulebar.duckdns.org`)"

networks:
    web_net:
        driver: bridge
