# https://hub.docker.com/r/linuxserver/sonarr
FROM --platform=linux/arm linuxserver/bazarr:latest

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	nfs-utils && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*


# add local files
COPY root/ /
