
FROM ghcr.io/chukysoria/duplicati:latest

RUN \
	echo "**** install packages ****" && \
	apt-get update && \
	apt-get install -y \
		iptables && \
	echo "**** cleanup ****" && \
	apt-get clean && \
	rm -rf \
	/tmp/* \
	/var/tmp/* \
	/var/lib/apt/lists/*
