# syntax=docker/dockerfile:1
FROM --platform=linux/arm lscr.io/linuxserver/radarr:arm32v7-4.5.2.7388-ls175

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	nfs-utils \
	iptables && \
 echo "**** clean up ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*

# add local files
COPY root/ /
