global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /config
    watch: true

entryPoints:
  tcp_web:
    address: ":8080"
    http:
      redirections:
        entryPoint:
          to: tcp_websecure
          scheme: https
          permanent: true

  tcp_websecure:
    address: ":8443"
  
  traefik:
    address: ":8090"
