#!/usr/bin/with-contenv sh

cd /opt/adguardhome || exit

exec \
    /opt/adguardhome/AdGuardHome -h 0.0.0.0 \
    -c /opt/adguardhome/conf/AdGuardHome.yaml \
    -w /opt/adguardhome/work \
    --no-check-update