global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
api:
  insecure: true

providers:
  docker:
     endpoint: unix:///var/run/balena.sock
     exposedbydefault: false
  file:
    directory: /etc/traefik
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      middlewares:
      - hsts-header@file
      tls:
        certResolver: letsencrypt
        options: modern@file

http:
  middlewares:
    hsts-header:
      headers:
        customResponseHeaders:
          Strict-Transport-Security: "max-age=63072000"


certificatesResolvers:
  letsencrypt:
    acme:
      email: chukysoria@gmail.com
      storage: /var/certs/acme.json
      dnschallenge:
        provider: duckdns
  letsencrypt-staging:
    acme:
      email: chukysoria@gmail.com
      caserver: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /var/certs/acme.json
      dnschallenge:
        provider: duckdns

tls:
  options:
    modern:
      minVersion = VersionTLS13