name: 'Release Drafter'

on:
  push:
    branches:
      - main
      - master

jobs:
  update_release_draft:
    name: Release
    uses: chukysoria/workflows/.github/workflows/new-release.yml@v1.0.7
    with:
      config-file: balena.yml
